### ISSUE TITLE
Q: Pipe CSV to file?

### ISSUE THREAD

**Issue by qosmy-michael** [cleishm/libneo4j-client#10]
Hi Chris

I really like the client!  I have a pretty simple question - and apologies in advance if it seems totally trivial -   how can I pipe csv output to a file?  

I tried various combinations of "|" and ">>" to no avail...

Thanks,

Michael

**Comment by cleishm** [comment]
It should work in a normal fashion, e.g.:

```
% neo4j-client --version
neo4j-client: 1.0.0
libneo4j-client: 1.0.0
% echo 'MATCH (n:Person) RETURN n;' | neo4j-client neo4j://neo4j:test@localhost > out.csv
% head -3 out.csv
"n"
"(:Person:Post{born:1957,name:""Kelly McGillis""})"
"(:Person:Post{born:1959,name:""Val Kilmer""})"
%
```

I just ran the above on my macbook, so it should work for you also. If not, let me know more detail about your environment?

Cheers,
Chris
