### ISSUE TITLE
neo4j_tostring returns quoted string

### ISSUE THREAD

**Issue by ttti07** [cleishm/libneo4j-client#11]
First of all, thank you for your fancy library with intuitive interface.

I'm implementing my graph db client using this library, but I have a small doubt about the behavior of the function `neo4j_tostring`.
If I print the return value of the function, the value is always quoted (e.g. `"my value"`). Of course, what I expected is `my value`, 
I didn't insert any quoted string to the graph, and also I confirmed it using the Neo4j web client.
Is there anything wrong with my code? Or, Is it what you intended?
I will grateful if you answer to this problem. :)

```cpp
    std::string queryStr = "MATCH (a:Item) RETURN a.name;";

    auto *queryResults = neo4j_run(session, queryStr, queryParam);
    auto *queryResult = neo4j_fetch_next(queryResults);
    while (queryResult) {
        auto neo4jValue = neo4j_result_field(queryResult, 0); 
        char buf[128];

        std::string val = neo4j_tostring(neo4jValue, buf, sizeof(buf));  // 'val' contains quoted string!
        output.push_back(val);

        queryResult = neo4j_fetch_next(queryResults);
    }
```

**Comment by cleishm** [comment]
Hi @ttti07,

First thing, it would be great if you could put these kind of questions on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j-client), as there's a much bigger community of Neo4j enthusiasts there who could also help answer these types of questions, or benefit from seeing the answers.

In this case, the function [`neo4j_tostring()`](https://cleishm.github.io/libneo4j-client/doc/latest/neo4j-client_8h.html#a61f578018b0de5cb4e19dbd07fab96a5) writes the value as it would appear as a literal value in Cypher. So strings are quoted.

If you want the string without the quotes, you can just get the value from the string using [`neo4j_string_value()`](https://cleishm.github.io/libneo4j-client/doc/latest/neo4j-client_8h.html#a73f4e61c323afb3f7abe675599beae65). Of course, that will only be valid if the value is a neo4j string, so check that first. Something like:

```C
    if (neo4j_instanceof(neo4jValue, NEO4J_STRING))
    {
        neo4j_string_value(neo4jValue, buf, sizeof(buf));
    }
    else
    {
        neo4j_tostring(neo4jValue, buf, sizeof(buf));
    }
```

Cheers,
Chris
