### ISSUE TITLE
Provide examples for iterating over a result set

### ISSUE THREAD

**Issue by buddha314** [cleishm/libneo4j-client#14]
It seems the StackOverflow tag is getting [no love](http://stackoverflow.com/questions/tagged/libneo4j-client).

I am looking for examples on usage for neo4j_client in C++. In the test suite I see the neo4j_result_t, but no example of iterating or calling fields by name. Is that possible?  I have also posted [this SO](http://stackoverflow.com/questions/40199212/iterate-over-results-in-neo4j-client-for-c)

**Comment by cleishm** [comment]
Sometimes it can take a while for love ;-)

Answered on [StackOverflow](http://stackoverflow.com/questions/40199212/iterate-over-results-in-neo4j-client-for-c).
