### ISSUE TITLE
neo4j_run returns NULL neo4j_result_stream_t and errno=22

### ISSUE THREAD

**Issue by borneq** [cleishm/libneo4j-client#17]
In Java code was:
	public List<Value> runQueryTransactions(String query, int counter) throws InterruptedException {
		try {
			List<Value> ret = new ArrayList<Value>();
			StatementResult result;
			result = session.run(query);
			if (result.hasNext()) {
				Record record = result.next();
				for (int i = 1; i <= counter; i++) {
					ret.add(record.get("tid_" + i));
				}
			}
			return ret;
		} catch (Exception ex) {
			System.out.println(ex.getMessage() + "\nError when create transactions, query=\n" + query);
			return null;
		}
	}

In C++:
std::vector<neo4j_value_t> Neo4J::runQueryTransactions(std::string query, int counter)
{
    try {
            std::vector<neo4j_value_t> ret;
            neo4j_result_stream_t *results = neo4j_run(session, query.c_str(), neo4j_null);
            if (results == NULL)
                 printf("errno=%d\n",errno);
            neo4j_result_t *record = neo4j_fetch_next(results);
            if (record)
            {
                for (int i = 1; i <= counter; i++)
                {
                    neo4j_value_t value = neo4j_result_field(record, i);
                    ret.push_back(value);
                }
            }
            neo4j_close_results(results);
            return ret;
    } catch (...) {
            printf("\nError when create transactions, query=%s\n",query.c_str());
            return std::vector<neo4j_value_t>();
    }
}

and query was:
MERGE (t_1:Transaction {
  tstamp: "2010-09-16 07:03:47",
  blockht: 80000,
  thash: "5a4ebf66822b0b2d56bd9dc64ece0bc38ee7844a23ff1d7320a88c5fdb2ad3e2",
  idtx: 80000,
  fee: 0,
  size: 158
            })
MERGE (t_2:Transaction {
  tstamp: "2010-09-16 07:03:47",
  blockht: 80000,
  thash: "c06fbab289f723c6261d3030ddb6be121f7d2508d77862bb1e484f5cd7f92b25",
  idtx: 80000,
  fee: 0,
  size: 134
            })
RETURN ID(t_1) as tid_1,
ID(t_2) as tid_2

For this query Java version returns array of values, whereas C++ version neo4j_run return NULL and errno=22

**Comment by borneq** [comment]
Is OK, error was because variable session was NULL;
should be "for (int i = 0; i < counter; i++)" instead "for (int i = 1; i <= counter; i++)"

**Comment by cleishm** [comment]
Ok - I'm glad you solved it!
