### ISSUE TITLE
libneo4j-client fail ubuntu

### ISSUE THREAD

**Issue by oumartraore** [cleishm/libneo4j-client#19]
Hi

I followed the build instructions and I had no errors while compiling libneo4j-client.
My #include <neo4j-client.h> header file is included without any errors. But when I want to use the functions of the library, the compiler returns an error (see error below). I use ubuntu 14.04, must I add a binary to its program, if I install the library in global

CMakeFiles/IoT_Model.dir/sources/serviceDAO/source/neo4jDAO.cpp.o: In function `neo4jDAO::neo4jDAO()':
/vagrant/sources/serviceDAO/source/neo4jDAO.cpp:15: undefined reference to `neo4j_client_init'
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/IoT_Model] Error 1
make[1]: *** [CMakeFiles/IoT_Model.dir/all] Error 2
make: *** [all] Error 2
root@vagrant-ubuntu-trusty-64:/vagrant/build#

Cdt

**Comment by oumartraore** [comment]
I solved the problem. I forgot to add the share libraries /usr/local/lib/libneo4j-client.so
You could add it in Readme.md, because there are people who do not read your logs :)

**Comment by cleishm** [comment]
Hi @oumartraore,

Usually one provides link flags like `-lneo4j-client -lssl -lcrypto -lm`, which is mentioned in the readme.

Did you use those flags?

Cheers,
Chris
