### ISSUE TITLE
Any plans to support building and using on Windows?

### ISSUE THREAD

**Issue by calzakk** [cleishm/libneo4j-client#2]

**Comment by cleishm** [comment]
Hi @calzakk,

It's already top of the TODO list: https://github.com/cleishm/libneo4j-client/wiki/TODO

It should also be pretty straight forward, as the code has been structured to isolate the parts that will likely be OS specific (network sockets and ssl). The most annoying will probably be creating the CMake file for use in Visual Studio.

However, I'm unlikely to work on that personally, as I don't have a windows development setup myself. So instead it's a great opportunity to contribute for someone in the community who has the interest, and has a windows development environment. And I'd be happy to give advice before and during development. If you're interested, or know someone who is, then please get in touch!

Cheers,
Chris

**Comment by calzakk** [comment]
Sorry Chris, I didn't see your TODO list!
Might be able to help with this later on, but I've only just started looking at Neo4j.

cal

**Comment by borneq** [comment]
When is planning support Windows?

**Comment by cleishm** [comment]
Just as soon as somebody contributes it. If you'd like to help, there's some discussion in #13.
