### ISSUE TITLE
Neo4j_run fails when running long queries

### ISSUE THREAD

**Issue by hisanor** [cleishm/libneo4j-client#21]
Thanks for sharing your beautiful code!

I have a question.
The function "neo4j_run" fails when running queries longer than 65530-65540.  And I am suspecting that it has  something to do with the "const char *statement" used in the "neo4j_run" function which has an obvious character size limit of 65536.  I also double checked that the same long query could be performed fine with other drivers (e.g. Neo4j Python Driver), so I think it is a problem with your code and not Neo4j itself.

Since it is not unusual to run a query longer than 65536 (e.g. obtain a sub-graph from a database given 10,000 node IDs), do you have any plans to fix this issue? 

Best,

Ryohei Hisano

**Comment by cleishm** [comment]
Hi @hisanor!

Wow. More than 65536 characters in a statement? That's a _huge_ statement, and I think quite unusual. Can I suggest you might prefer to use [query parameters](http://neo4j.com/docs/developer-manual/current/cypher/syntax/parameters/)? That would be the prefered way to pass things like node IDs. It would also save the server having to parse such a long statement.

That said, I added a [test for handling a long statement](https://github.com/cleishm/libneo4j-client/commit/4ef523a50b27ebe83fbf226ead475cf39adc2f79). It asserts that a statement of length 65537 gets sent successfully over the network, without any error. Note also that `const char *statement` is a pointer type - it points to a null-terminated sequence of characters, and doesn't encode any detail about the length.

Can you give me more detail about the error? Perhaps some code to reproduce it myself?

Cheers,
Chris

**Comment by hisanor** [comment]
Thank you for your fast response.

You are right.  I should have used query parameters.
Once using query parameters everything is fine!

Just for your information, the query I was testing with was (in Python)

q = """
MATCH p=(n)-[r]-(m)
WHERE ID(n) IN {}
AND ID(m) IN {}
RETURN p
""".format(Nodes,Nodes)

where Nodes are list that contains ID numbers in int.
And I passed this statement using pybind11.
The curious thing for me was that this worked until 
"q"'s length was around 65536, but somehow resulted in error
for longer queries (erro num -16 is what I read).

But anyway, I was able to handled the issue using query parameters.  Thank you very much :-)

Best,

Ryohei

**Comment by cleishm** [comment]
Great, I'm glad to hear you fixed it.

I'm suspecting the issue with long strings to be an error in the python binding you're using. The -16 error number likely comes from there also (in this library, -16 would indicate a closed connection).

Do you have a link to the binding source code repository? I'd suggest raising an issue there.

Cheers,
Chris
