### ISSUE TITLE
Methods for opening and working with .db Neo4j files

### ISSUE THREAD

**Issue by zadlg** [cleishm/libneo4j-client#23]
It will be nice if we could open a .db file in order to work on a database.!

**Comment by jexp** [comment]
You can use neo4j-shell -path for that

**Comment by zadlg** [comment]
I meant for the C++/C API

**Comment by cleishm** [comment]
Hi @zadlg!

I’m curious why you would even want that.

Regardless of the reason, the format and use of those .db files is an internal detail of Neo4j server, and there is no way to provide support for directly reading/writing it using this library or in any other program.

I also strongly recommend against directly accessing those files anyway, even using neo4j-shell with the —path option (which essentially starts a server inside the shell process). You should run neo4j server and then access the server over the network using a driver (like this one).

Cheers,
Chris
