### ISSUE TITLE
Small error in example in API documentation

### ISSUE THREAD

**Issue by SijmenSchoon** [cleishm/libneo4j-client#24]
Hi there. I'm not sure if this is the right repo for this, but I found a bug in the API documentation on the [homepage](https://neo4j-client.net/#api_documentation). I'll let a diff explain the issue:

```diff

     neo4j_result_t *result = neo4j_fetch_next(results);
-    if (results == NULL)
+    if (result == NULL)
     {
         neo4j_perror(stderr, errno, "Failed to fetch result");
```

EDIT: This issue does not exist in `/master/README.md` in this repository.

**Comment by cleishm** [comment]
Fixed via b48a3ac5c257f0c2be6f075134d6972ec7303ad6.

Thanks for catching that!
