### ISSUE TITLE
Need ppa for bionic

### ISSUE THREAD

**Issue by andrzej-borucki** [cleishm/libneo4j-client#28]
I have installed Mint 19 Tara beta. It has some benefits like Qt5 libraries.
If I try
sudo add-apt-repository ppa:cleishm/neo4j
is error: no files for bionic.

**Comment by cleishm** [comment]
Hey @andrzej-borucki,

Do you have instructions for building that? Would love a PR, or at least a document that describes the process.

Cheers,
Chris

**Comment by andrzej-borucki** [comment]
W dniu 25.06.2018 o 01:43, Chris Leishman pisze:
>
> Hey @andrzej-borucki <https://github.com/andrzej-borucki>,
>
> Do you have instructions for building that? Would love a PR, or at 
> least a document that describes the process.
>
> Cheers,
> Chris
>
>
Hi, I have built it with sources, it was simple:
sudo apt-get install libncurses-dev libssl-dev
build editline,libcypher-parser, and libneo4j-client

Thanks.

**Comment by mangohero** [comment]
Hi @cleishm ,

I was installing libneo4j on Ubuntu. I tried:
sudo add-apt-repository ppa:cleishm/neo4j

But there is an error:
Err:8 http://ppa.launchpad.net/cleishm/neo4j/ubuntu bionic Release             
  404  Not Found [IP: 91.189.95.83 80]
E: The repository 'http://ppa.launchpad.net/cleishm/neo4j/ubuntu bionic Release' does not have a Release file.

Could you please help solve this problem? Thanks!

**Comment by cleishm** [comment]
I've updated launchpad such that the packages are published to bionic. Thanks for the heads up!

**Comment by cleishm** [comment]
Please note that the latest version of libneo4j-client is actually available in the stable distribution, without the need for adding the ppa.

I should probably update the documentation to reflect that!

**Comment by mangohero** [comment]
@cleishm Thanks! It's solved. Now I can install it!
