### ISSUE TITLE
Building with gcc8

### ISSUE THREAD

**Issue by aphorisme** [cleishm/libneo4j-client#29]
Hello! I'm trying to build libneo4j-client on Fedora 28. Running `make clean check`  after cloning the repo and going through `./autogen.sh` as well as ` ./configure.sh`, I get the following error:

```
client_config.c:494:5: Fehler: »strncpy« angegebene Grenze 1024 ist genau die Größe des Ziels [-Werror=stringop-truncation]
     strncpy(username_buf, (config->username != NULL)? config->username : "",
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             sizeof(username_buf));
```

(Translated it should be something like: "strncpy" given limit 1024 is exactly the size of the target). 
As far as I can see, these kind of warnings (which are turned into errors here) are added in gcc8 to check for possible bugs where strings aren't null-terminated because of `strncpy`. 

There are 3 locations where gcc posts a warning:

 - `client_config.c:494`
 - `client_config.c:496`
 - `print.c:52`

If I understand it right, there might be a bug at `client_config.c:494,496` whenever `config->username` or `config->password` has length greater then `NEO4J_MAXUSERNAMELEN`. If this is the case, then `username_buf` resp. `password_buf` is **not** null-terminated. If there is no need that the strings are null-terminated, one might consider memcpy instead.

I'm not sure about the occurrence in `print.c`. 

A workaround is to wrap

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstringop-truncation"
    strncpy(username_buf, (config->username != NULL)? config->username : "",
            sizeof(username_buf));
    strncpy(password_buf, (config->password != NULL)? config->password : "",
            sizeof(password_buf));
#pragma GCC diagnostic pop
```
into `client_config.c` (and in a similar fashion into `print.c`). But the bug might still appear, if it is possible to get `neo4j_config_t.username` or `neo4j_config_t.password` to be greater then `NEO4J_MAXUSERNAMELEN` in length.

**Comment by cleishm** [comment]
Thanks for reporting this, @aphorisme.

I've fixed these now in master. Fortunately, none of the potential cases of non-null-termination would have caused an issue, but it's good to fix them anyway.

Cheers,
Chris
