### ISSUE TITLE
CREATE query size limit?

### ISSUE THREAD

**Issue by orinatic** [cleishm/libneo4j-client#31]
Hello!

I'm getting a query size related error (I think?) with both the c api and also the command line client. When I run the attached file, using `neo4j-client -u neo4j -p <pass> -o result.out -i <file>  localhost`, I get the error of `unexpected error: Connection closed` (and no items are added)

I've attached the server and client logs (generated by running with -vvv) as well.

Notably, removing any single line from the file causes it to succeed. If I use the c api to call neo4j_run, I get the same error (neo4j_check_failure gives me -16, which is NEO4J_CONNECTION_CLOSED)

Running `cat <file> | ./cypher-shell -u neo4j -p <pass> --format plain` does work, and I can use that as a workaround, but I'd ideally like to be able to use the c API.

Thank you!
[input_file.txt](https://github.com/cleishm/libneo4j-client/files/2543387/input_file.txt)
[server.log](https://github.com/cleishm/libneo4j-client/files/2543392/debug.log)
[client_log.txt](https://github.com/cleishm/libneo4j-client/files/2543398/client_log.txt)

**Comment by cleishm** [comment]
Ok, I tracked down the issue and created a fix (620c36445e3d75833365626bb27e1b870d2f5ba1). I'll push new packages this week to all the right places.

**Comment by orinatic** [comment]
Thank you! Any chance you can point me to somewhere that talks about how to parameterize queries?

**Comment by cleishm** [comment]
https://neo4j.com/docs/developer-manual/current/cypher/syntax/parameters/

In the libneo4j-client API, you pass the arguments as a map in the `neo4j_run` command (rather than `neo4j_null` as is used in the README example).

**Comment by orinatic** [comment]
Thank you!
