### ISSUE TITLE
neo4j_tostring fills buffer with trash

### ISSUE THREAD

**Issue by borneq** [cleishm/libneo4j-client#32]
I have first fill neo4j database with one transaction:
```
MERGE (t:Transaction {
  tstamp: "2018-11-14 04:03:14",
  blockht: 550001,
  thash: "0000000000000000000000000000000000000000000000000000305f68736168",
  fee: -390842024046,
  size: 8
})
MERGE (a_0:Address {btc_address: "0MINEDxCOINBASE0000000000000000000"})
MERGE (a_0)-[sf_0:SEND_FROM {amount:0,indx_tx:0,indx_io:0,type:0}]->(t)
MERGE (a_1:Address {btc_address: "0MINEDxCOINBASE0000000000000000000"})
MERGE (a_1)-[sf_1:SEND_FROM {amount:0,indx_tx:0,indx_io:1,type:0}]->(t)
MERGE (a_2:Address {btc_address: "bc1address_0_0"})
MERGE (a_2)<-[st_0:SEND_TO {amount:0,indx_tx:0,indx_io:0,type:1}]-(t)
MERGE (a_3:Address {btc_address: "bc1address_0_1"})
MERGE (a_3)<-[st_1:SEND_TO {amount:1,indx_tx:0,indx_io:1,type:1}]-(t)
MERGE (a_4:Address {btc_address: "bc1address_0_2"})
MERGE (a_4)<-[st_2:SEND_TO {amount:2,indx_tx:0,indx_io:2,type:1}]-(t)
MERGE (a_5:Address {btc_address: "bc1address_0_3"})
MERGE (a_5)<-[st_3:SEND_TO {amount:3,indx_tx:0,indx_io:3,type:1}]-(t)
MERGE (a_6:Address {btc_address: "bc1address_0_4"})
MERGE (a_6)<-[st_4:SEND_TO {amount:4,indx_tx:0,indx_io:4,type:1}]-(t)
```
next, match 
```
match (t:Transaction {thash: "0000000000000000000000000000000000000000000000000000305f68736168"})
match (a:Address)<-[rel:SEND_TO{indx_io: 0}]-(t)
return rel.amount as amount, a.btc_address as address 
```
returns correct values in http://127.0.0.1:7474/browser/: 0 and "bc1address_0_0"
but if I use it with c+ connector:
```
 bool IndepNeo::getAmountAddress(Neo4J *neo4j, string txHash, int ioIdx, string &address, int64_t &amount) {
     string queryStr =
         (string)"match (t:Transaction {thash: \"" + txHash + "\"})\n" +
       "match (a:Address)<-[rel:SEND_TO{indx_io: " + to_string(ioIdx) +  "}]-(t)\n" +
       "return rel.amount as amount, a.btc_address as address";
     vector<neo4j_value_t> results = neo4j->runQueryTransactions(queryStr, 2);
     printf("results.size()=%d\n",results.size());
     if (results.size()<2) return false;
     amount = results[0]._vdata._int;
     char buf[80];
     memset(buf, 0, sizeof(buf));
     neo4j_tostring(results[1], buf, 80);
     printf("readed from neo4j_tostring: %s\n",buf);
     address = buf;
     return true;
}
```
using neo4j_tostring, in buf is trash

**Comment by cleishm** [comment]
Hi @borneq,

Which wrapper for this library are you using? `runQueryTransactions` is not part of the API of this library.

Also, please ensure you're using the accessor methods for bringing data out of the results. Do not use `_vdata` (or any `_` prefixed attribute), as these are internal and may not be structured as you believe them to be. The complete API for this library is published here: http://neo4j-client.net/doc/latest/neo4j-client_8h.html

Cheers,
Chris

**Comment by borneq** [comment]
I am using 
std::vector<neo4j_value_t> Neo4J::runQueryTransactions(std::string query, int counter)
where is 
```
neo4j_result_stream_t *results = neo4j_run(connection, query.c_str(), neo4j_null);
			if (results == NULL)
                throw Exception(formatString("neo4j_run error, errno:%d",errno), NEO4J_EXCEPTION_QUERY);
            neo4j_result_t *record = neo4j_fetch_next(results);
            if (record)
            {
                for (int i = 0; i < counter; i++)
                {
                    neo4j_value_t value = neo4j_result_field(record, i);
                    ret.push_back(value);
                }
            }
            neo4j_close_results(results);
```
and several lines of code to work with exceptions (for example reconnect in special cases)
If I call neo4j_close_results(results), values in ret vector become to have not access?

**Comment by borneq** [comment]
"I also notice that you're also only obtaining the first result, and not iterating until neo4j_fetch_next(results) returns NULL"
if I for example have "return rel.amount as amount, a.btc_address as address", I must call function neo4j_fetch_next twice or call it once and call neo4j_result_field(record, 0) and neo4j_result_field(record, 1) ? In this case we have two results or two fields?

**Comment by cleishm** [comment]
A Cypher query returns a sequence of results (records), where each result contains multiple fields.

So a query like "MATCH (a)-[rel]->() RETURN rel.amount as amount, a.btc_address as address" could return many results, depending on how many matches it finds for the pattern, and each result will contain two fields (amount and address).

Of course, if you know that there is only one result from your query, then you can just call `neo4j_fetch_next` the one time. However, your generic `runQueryTransactions` doesn't have any way to know that is always true.

If you want to wrap it into a C++ API, I'd probably change the signature of that method to `std::vector<std::vector<neo4j_value_t>> Neo4J::runQueryTransactions(std::string query)`.

(Also, rather than passing in `counter`, use [`neo4j_nfields(results)`](http://neo4j-client.net/doc/latest/neo4j-client_8h.html#a75840eac49113d9dd2acbab4586a5002) to determine the number of fields in each result record.

**Comment by cleishm** [comment]
Hopefully this helped get things working for you! Closing this issue now.
