### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by srooznow** [cleishm/libneo4j-client#4]
I get this compilation error when including the header file neo4j-client.h:
> #g++ neo.cpp -L/usr/lib64 -lneo4j-client
In file included from neo.cpp:1:0:
 neo4j-client.h:1946:26: error: expected "," or "..." before "buf" 
 char ** restrict buf, size_t * restrict bufcap

my system info is:
> "Red Hat Enterprise Linux Server" VERSION="7.2 (Maipo)" 
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

**Comment by cleishm** [comment]
Hi @srooznow,

I suspect this is the same as #3 aims to fix. I'm just checking a couple of options to do that, and then we should have a fix.

Meanwhile, in your C++ code, can you try adding `#define restrict __restrict__` before including the header?

Cheers,
Chris

**Comment by srooznow** [comment]
Thanks Chris,
I added ```#define restrict __restrict__``` before ```#include <neo4j-client.h>``` and the issue is resolved.

**Comment by cleishm** [comment]
Thanks for the feedback @srooznow! It should now be resolved, and I'll make a new release with the updated header.
