### ISSUE TITLE
]Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by Natarajan77** [cleishm/libneo4j-client#50]
➜  Downloads clang++ -Wall  neo4j.cpp -o neo
Undefined symbols for architecture x86_64:
  "_neo4j_client_cleanup", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_client_init", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_close", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_close_results", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_connect", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_fetch_next", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_null", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_perror", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_result_field", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_run", referenced from:
      _main in neo4j-e6e06b.o
  "_neo4j_tostring", referenced from:
      _main in neo4j-e6e06b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
➜  Downloads

**Comment by cleishm** [comment]
I'm not sure what codebase this is from, but `neo4j.cpp` is not part of this project.

**Comment by Natarajan77** [comment]
Neo4j.cpp is a file which I have written and has the code 

I need to do some bench mark using c++ and neo4j to find out the performance for create , update and delete can u pls share some example and details thanks

**Comment by cleishm** [comment]
Please refer to https://github.com/cleishm/libneo4j-client#api-documentation, and otherwise post your quesitons on stackoverflow.

**Comment by Natarajan77** [comment]
Open source version of Neo4j does it have c++ driver support? 

The link shared looks like it is for c and not c++ "https://github.com/cleishm/libneo4j-client#api-documentation"

**Comment by cleishm** [comment]
neo4j-client is a C based library. Like all C libraries, it can be used directly in C++.
