### ISSUE TITLE
Brew tap issue

### ISSUE THREAD

**Issue by gregleleu** [cleishm/libneo4j-client#54]
Hi, 
Homebrew has started giving me the following error at every update since a few days ago.
Did anything change?
```
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/cleishm/homebrew-neo4j failed!
```

Thanks,
Greg

**Comment by cleishm** [comment]
Ah! Thanks for the heads up on this.

The branch names have changed, which was causing this issue. I've updated the homebrew formula, so it should be ok now.
