### ISSUE TITLE
What is the format the neo4j client returns data in?

### ISSUE THREAD

**Issue by new-gen23** [cleishm/libneo4j-client#61]
Hi,
I used the client to pull some data from a neo4j. The neo4j database within contains entities created by the tool bloodhound (https://github.com/BloodHoundAD/BloodHound). 

The connection works so far, but I am at a loss what the client returns? The query was: 
"match (n:Computer) RETURN n"

A sample string returned by the client looks like this:
```
(:Base:Computer{operatingsystem:"Windows Server 2008",name:"COMP00001.TESTLAB.LOCAL",owned:false,enabled:true,objectid:"S-1-5-21-883232822-274137685-4173207997-1000",domain:"TESTLAB.LOCAL"})
```

However, this it neither XML nor JSON (though it looks similar to JSON). Still, every parser I tried said that the format is broken. Do I really need to split/parse the string myself? That would be very error prone...

**Comment by cleishm** [comment]
I’m guessing your query is written to return a node, rather than properties. So it’s using the Cypher node format for the output.

Try returning just the properties you want. You can format them into a map as part of the cypher query (e.g. a map projection) and you’ll get JSON compatible output.

**Comment by new-gen23** [comment]
I see, that makes sense. I think. The query would return the edges in the graph, not the relations. So I guess you could call a single return line "a node with properties". I will first check if there is a c++ Cypher parser, otherwise I will follow your advice.

**Comment by cleishm** [comment]
I'm saying that your query probably looks like `MATCH (x)-[y]->(z) RETURN z`. That would return the node matched as `z` (or you could be returning the edge `y` as `RETURN y`). Instead, return the properties as a [map projection](https://neo4j.com/docs/cypher-manual/current/syntax/maps/#cypher-map-projection-examples), e.g. `RETURN z{.*}`. You could also pick specific properties, e.g. `RETURN z{.foo, .bar}`.
