### ISSUE TITLE
Connection refused on OS X yosemite

### ISSUE THREAD

**Issue by dariux881** [cleishm/libneo4j-client#7]
Hello,
I tried to establish a connection by both command line and in my C++ project. 
In a "secure" version I received:
OpenSSL error: 336130315:SSL routines:SSL3_GET_RECORD:wrong version number

If I try with an insecure connection, I received:
connection to 'neo4j://localhost:7474' failed: Could not agree on a protocol version

How could I repair? 
An insecure connection is good for me.

**Comment by cleishm** [comment]
Hi @dariux881,

I prefer if you use [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j-client) for questions on usage. Make sure to use the tag `neo4j-client`.

Cheers,
Chris

**Comment by cleishm** [comment]
Hi @dariux881,

I haven't seen the question on StackOverflow as yet. I'll keep an eye out for it, but I believe you're using the wrong port in your URL.

I'll close this issue now.

Cheers,
Chris
