### ISSUE TITLE
implicit declaration of function

### ISSUE THREAD

**Issue by kkos** [cleishm/libneo4j-client#8]
An error occurs in my env.
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

interactive.c: In function ‘check_line’:
interactive.c:271:5: error: implicit declaration of function ‘cypher_quick_uparse’ [-Werror=implicit-function-declaration]
     if (cypher_quick_uparse(line, length + 1, check_processable, &process,
     ^
cc1: all warnings being treated as errors

**Comment by cleishm** [comment]
Hi @kkos,

You likely have an older version of [libcypher-parser](https://git.io/libcypher-parser) installed.

As you're building from the source tree, and you recently pulled updates, you'll need to re-run `./autogen.sh` and `./configure`. You should then get an error that the correct version of libcypher-parser is unavailable.

Cheers,
Chris

**Comment by kkos** [comment]
I understand.
