### ISSUE TITLE
`neo4j-client` should direct users toward `:help` command

### ISSUE THREAD

**Issue by cheerfulstoic** [cleishm/libneo4j-client#9]

**Comment by cleishm** [comment]
I'm not sure it should be for _any_ error message. But certainly the "unknown command" message, and perhaps the "not connected" error.

Want to do a PR?

**Comment by cheerfulstoic** [comment]
The problem is that I struggled for a while without even knowing that commands start with `:`, so I had output like this:

```
neo4j> help;
Invalid input 'h': expected <init> (line 1, column 1 (offset: 0))
"help"
 ^
```

Sadly I have only sad slivers of time lately to work on trying to get out a version of the Neo4j.rb gems which support Bolt, so I don't really have the time for a PR on this (unless it is for all errors, then I suppose it probably wouldn't be too hard)

**Comment by cleishm** [comment]
Ah, got it. Still, I don't think we should just tack on `\n(need help? Type :help)` as it'd be unhelpful verbosity on every real error. E.g.:

```
neo4j> mathc (n) return n;
Invalid input 'h': expected 'c/C' (line 1, column 4 (offset: 3))
"mathc (n) return n"
    ^
(need help? Type :help)
neo4j> 
```

I guess we could try to check for some common cases like `help;`, and add then hint. Or perhaps only append the hint once per interactive session?

**Comment by cheerfulstoic** [comment]
I was thinking that I've seen solutions to this before.  I didn't want to go to the trouble of installing postgres / mysql, but this is what `sqlite` gives:

```
[brian@MacBook-Air.local: 22:41:10] ~
 $ sqlite3 test.sqlite
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> oaeu;
Error: near "oaeu": syntax error
```

I think that having it at the start is a great way to take care of the problem.

This may be a separate issue, but outputting the version of `neo4j-client` would be nice.  The version of the DB would be good too, if you can get it.  I think `psql` does that

**Comment by cleishm** [comment]
Adding it at the start of an interactive session is trivial.

The version is also avail with `neo4j-client --version`. It would be nice if we could report the server version (when connected), but that would need neo4j to send it as part of the SUCCESS response to INIT.

**Comment by cleishm** [comment]
@cheerfulstoic - how about 56115bc01d890bedac7a20b79072d57c819e2947?

**Comment by cheerfulstoic** [comment]
Seems great, thanks!

**Comment by cleishm** [comment]
The changes in 56115bc01d890bedac7a20b79072d57c819e2947 are now merged.

**Comment by cheerfulstoic** [comment]
Awesome, thanks!
